Table User {
  Id int [pk, increment]
  Email varchar(256)
  UserName varchar(256)
  PasswordHash varchar
}

Table Ticket {
  Id int [pk, increment]
  Title varchar(120)
  Description varchar(2000)
  Status varchar // 'Open' | 'Closed'
  CreatedAt datetime

  AuthorId int [ref: > User.Id]
  AssignedToId int [ref: > User.Id, note: 'nullable']
}

Table Comment {
  Id int [pk, increment]
  Content text
  CreatedAt datetime

  AuthorId int [ref: > User.Id]
  TicketId int [ref: > Ticket.Id]
}

Table Attachment {
  Id UUID [pk]
  ContentType varchar(128)
  OriginalFileName varchar(255)
  CreatedAt datetime

  UploaderId int [ref: > User.Id]
}

Table TicketAttachment {
  TicketId int [ref: > Ticket.Id]
  AttachmentId UUID [ref: > Attachment.Id, unique]

  indexes {
    (TicketId, AttachmentId) [pk]
  }
}

Table Tag {
  Id int [pk, increment]
  Name varchar
  Description varchar
}

Table TicketTag {
  TicketId int [ref: > Ticket.Id]
  TagId int [ref: > Tag.Id]

  indexes {
    (TicketId, TagId) [pk]
  }
}

Table Vote {
  TicketId int [ref: > Ticket.Id]
  VoterId int [ref: > User.Id]
  Value int // 1 (Upvote) or -1 (Downvote)
  CreatedAt datetime

  indexes {
    (TicketId, VoterId) [pk]
  }
}

Table TicketStatusChange {
  Id int [pk, increment]
  FromStatus varchar
  ToStatus varchar
  ChangedAt datetime

  TicketId int [ref: > Ticket.Id]
  ChangedByUserId int [ref: > User.Id]
}

Table InviteCode {
  Code varchar [pk]
  CreatedAt datetime
  ExpiresAt datetime
}
