Table User {
  Id int [pk, increment]
  Email varchar(256)
  UserName varchar(256)
  PasswordHash varchar
}

Table Issue {
  Id int [pk, increment]
  Title varchar(120)
  Description varchar(2000)
  Status varchar // 'Open' | 'Closed'
  CreatedAt datetime

  AuthorId int [ref: > User.Id]
  AssigneeId int [ref: > User.Id, note: 'nullable']
}

Table Comment {
  Id int [pk, increment]
  Content varchar(2000)
  CreatedAt datetime

  AuthorId int [ref: > User.Id]
  IssueId int [ref: > Issue.Id]
}

Table Attachment {
  Id UUID [pk]
  ContentType varchar(128)
  OriginalFileName varchar(255)
  CreatedAt datetime

  UploaderId int [ref: > User.Id]
}

Table IssueAttachment {
  IssueId int [ref: > Issue.Id]
  AttachmentId UUID [ref: > Attachment.Id, unique]

  indexes {
    (IssueId, AttachmentId) [pk]
  }
}

Table CommentAttachment {
  CommentId int [ref: > Comment.Id]
  AttachmentId UUID [ref: > Attachment.Id, unique]

  indexes {
    (CommentId, AttachmentId) [pk]
  }
}

Table Tag {
  Id int [pk, increment]
  Name varchar(50) [unique]
  Description varchar(2000)
}

Table IssueTag {
  IssueId int [ref: > Issue.Id]
  TagId int [ref: > Tag.Id]

  indexes {
    (IssueId, TagId) [pk]
  }
}

Table Vote {
  IssueId int [ref: > Issue.Id]
  VoterId int [ref: > User.Id]
  Value int // 1 (Upvote) or -1 (Downvote)
  CreatedAt datetime

  indexes {
    (IssueId, VoterId) [pk]
  }
}

Table IssueStatusChange {
  Id int [pk, increment]
  FromStatus varchar
  ToStatus varchar
  ChangedAt datetime

  IssueId int [ref: > Issue.Id]
  ChangedByUserId int [ref: > User.Id]
}

Table InviteCode {
  Code varchar(64) [pk]
  CreatedAt datetime
  ExpiresAt datetime
}
